### ISSUE TITLE
mommy moves my promt to the left

### ISSUE THREAD

**Issue by peat734** [FWDekker/mommy#120]
For some reason mommy moves my prompt to the left
![image](https://github.com/FWDekker/mommy/assets/94827899/1d35bb1b-4d2d-4d15-8131-66c9fccb11a4)

my .zshrc file
```export ZSH="$HOME/.oh-my-zsh"
plugins=(git zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

clear
colorscript -e panes
autoload -U colors && colors
PS1="%B%{$fg[red]%}[%{$fg[yellow]%}%n%{$fg[green]%}@%{$fg[blue]%}%M %{$fg[magenta]%}%~%{$fg[red]%}]%{$reset_color%}$%b "
RPS1="$(mommy -1 -s $?)"
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.cache/zsh/history
export PATH=/home/peat/.local/bin:$PATH
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)               # Include hidden files.
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 2>/dev/null
```

**Comment by FWDekker** [comment]
this issue is worked around in the readme (under "shell integration" > "zsh"), but it's easy to miss since i don't actually explicitly mention this issue, and don't explain why it works the way it does.

so, firstly, note that if you do `RPS1="$(mommy -1 -s $?)"`, then `RPS1` will be set when `.zshrc` is loaded, and won't ever update. if you want `RPS1` to re-run after every command, then you should replace the double quotes (`"`) with single quotes (`'`), so now `RPS1` is just a literal string, and then you should also add `set -o PROMPT_SUBST` to your `.zshrc`, so that zsh knows that that string is a command that should be evaluated again each time.

as for your main issue, zsh is a bit weird with colour codes. mommy uses normal ansi escape codes (like `\e[31m`, where `31` specifies a red foreground), but when zsh creates the `PS1` and `RPS1` prompts, it thinks those ansi escape codes actually take up space, and will move the caret accordingly. you can zsh to not do this by wrapping the ansi escape code in `%{ ... %}`, but there is currently no clean way to do this within mommy's `MOMMY_COLOR` option. therefore, the best alternative is to set `MOMMY_COLOR=` (i.e. disable mommy's colour feature), and then put your desired zsh-specific colour codes in `MOMMY_PREFIX`, and then clear the colour codes in `MOMMY_SUFFIX`. you can use this snippet from the readme:
```sh
MOMMY_COLOR=""
MOMMY_PREFIX="%F{005}/%F{006}"
MOMMY_SUFFIX="~%f"
```
here, `%F{005}` is a zsh colour code, and `%f` resets the colours. using `%F{005}/%F{006}` means that mommy will randomly choose between colour 5 (pink) and colour 6 (cyan). [you can also use this handy xterm color code chart](https://upload.wikimedia.org/wikipedia/commons/1/15/Xterm_256color_chart.svg) to see which number means what colour.

please let me know if this solves your issue, and tell me if you have more questions~

**Comment by peat734** [comment]
It worked! Thanks a lot
