### ISSUE TITLE
add to fedora copr

### ISSUE THREAD

**Issue by natawie** [FWDekker/mommy#39]
seeing how there's already an rpm available, it probably won't be too much work + there'll be updates through dnf instead of downloading them manually

**Comment by FWDekker** [comment]
cool idea! i was planning on ironing out some small issues with the homebrew and aur packages i created last weekend first, but after that i'll look into copr ^^

**Comment by FWDekker** [comment]
some notes while I was browsing for information about copr:

* it looks like [this is copr](https://copr.fedorainfracloud.org/) and it will build packages for fedora. not sure if that means it will also work nicely for other rpm systems such as opensuse and stuff? maybe I need [build.opensuse.org](https://build.opensuse.org/) for that?
* [here is a tutorial on copr with screenshots](https://docs.pagure.org/copr.copr/screenshots_tutorial.html)
* i need to create an _srpm_, which is a _source rpm_. currently, this is done automatically by fpm, and that doesn't really have an automatic way of extracting the srpm it creates :( so I need to create my own srpm similar to how i created a `PKGBUILD` for arch. i should think of ways to somehow incorporate those related repositories into this one. like, create a sub-directory `build_system`  in this repo, with one directory for each build system (homebrew, aur, copr, and other ones?) and then sync those with their respective upstreams on each merge with `main`. but that sounds like a bad idea because i cannot force-push, but im also too lazy to have to manually keep several repos synchronised, blegh. isn't there some tool like fpm that also does distribution?

**Comment by FWDekker** [comment]
hey! good news, i've managed to get mommy onto copr. [you can check the project here](https://copr.fedorainfracloud.org/coprs/fwdekker/mommy/)

the repositories are currently empty, but as soon as there is a new mommy release, copr will be triggered to create new builds. (i already tested the full pipeline in a temporary project on copr that i've now deleted.)

**after mommy v1.2.3 releases** (probably later this weekend) you can install mommy from copr as follows:
```shell
sudo dnf copr enable fwdekker/mommy
sudo dnf install mommy
```
(you may also need to `sudo dnf install dnf-plugins-core` to enable the copr plugin for dnf.)

while installing mommy you may be asked to verify a pgp key fingerprint; it probably suffices to verify that the "From:" fields equals `https://download.copr.fedorainfracloud.org/results/fwdekker/mommy/pubkey.gpg`. (i will explicitly mention the key's fingerprint in the readme... once it has been generated by copr, which happens after the first build)

i'll leave another comment here once v1.2.3 has been released and the copr builds are done. (especially the first build might take a while; today i had to wait 4 hours in my test project.)

either way, let me know if you have any suggestions or comments or tips on using/installing mommy (on fedora-based systems or in general)

**Comment by FWDekker** [comment]
mommy v1.2.3 has been released, and [the copr build has been completed](https://copr.fedorainfracloud.org/coprs/fwdekker/mommy/build/5645213/). you should now be able to install mommy as follows:
```shell
sudo dnf copr enable fwdekker/mommy
sudo dnf install mommy
```
(you will also need to install the `dnf-plugins-core` package if you don't have it already.)
the package should be signed with a key with fingerprint `E332 C8E6 ADAA 58E4 1974  7CE2 CE16 3CFF 9F79 DD8A`

thank you for opening this issue! i thought it was really fun and interesting to learn about the fedora packaging ecosystem! i'll close this issue now, but feel free to leave another comment / open an issue if you need help, have questions, or have other suggestions ^^
