### ISSUE TITLE
i do not have config file

### ISSUE THREAD

**Issue by artble** [FWDekker/mommy#67]
i tried finding or downloading config file but i cant find it, im new to linux so i may just be stupid, but can sb tell me what can i do?

**Comment by FWDekker** [comment]
hiya! mommy works fine without a config file, she'll just use the default settings. if there are any settings you want to change, you can create a new file at `~/.config/mommy/config.sh`. (the `~` is an abbreviation for your home directory, so for me it would be `/home/florine/.config/mommy/config.sh`.) you can create a new file using a program like KWrite, Gedit, nano, Sublime Text, vim, VS Code, or something similar~

if you have a config file at `~/.config/mommy/config.sh`, then mommy will first load the defaults, and then any settings defined in `~/.config/mommy/config.sh` will _override_ the defaults~

i hope this helps. please let me know if you're stuck somewhere or have other questions :-)

**Comment by artble** [comment]
Hi! how to create new file at ~/.config/mommy/config.sh ? I also tried to go to .config, I made a mommy file with > (there wasn't any), but i can't create another config in it. I know I have nano because i used it to modify zshrc to make mommy apear automaticaly but idk how to make a new file in it. I tried to log in ssh (ssh user_name@host_ip_address, but it denys me connection, do you think I should try other programs you mentioned or to do sth else? 

Thank you for help, sorry for the trouble :)

**Comment by FWDekker** [comment]
using nano, you can just write `nano ~/.config/mommy/config.sh` and then add your configuration in the file. for example, add the following line:
![screenshot of the nano editor showing the mommy config file containing only the line `MOMMY_COLOR="163"`](https://github.com/FWDekker/mommy/assets/13442533/ffc0e596-0d4d-4142-82d1-355241543078)
and press <kbd>Ctrl</kbd><kbd>X</kbd>, type `Y`, and press <kdb>Enter</kbd> to save the file.
if you then run `mommy echo test` you'll see that her text is in a pink-ish colour~

you mentioned using `>`. instead of using nano you could also do
```shell
echo 'MOMMY_COLOR="163"' > ~/.config/mommy/config.sh
```
and you will also end up with a config file containing only the line `MOMMY_COLOR="163"`. but note that using `>` this way will _overwrite_ the file, so if you had made any other changes those would be lost. for config files i'd just use nano if i were you~

you also mentioned ssh. ssh is for connecting to a different computer over the network. unless you're trying to set up mommy remotely, you don't need it here~

**Comment by artble** [comment]
Thank You, but I have [Error writing ~/.config/mommy/config.sh: Not a directory] (instead of ~ i have /home/nosacz, but i think that this doesn't change much) and i can't save it.

**Comment by artble** [comment]
ok i made with mkdir (so it is directory) all files named in command and ill try now

**Comment by artble** [comment]
OK I GOT IT
I had to create these files as directory except for the config.sh, which was made by nano command.

Thank You again, I couldn't do it without your help. I wish you have a great day :D

**Comment by FWDekker** [comment]
oh of course, i'm sorry, i should have noticed that. but i'm glad to hear you got it working! cheers! feel free to reopen the issue, open a new issue, or leave another comment if you have more questions ^^
